### ISSUE TITLE
module name 与示例引用不一致

### ISSUE THREAD

**Issue by lesismal** [antlabs/tinyws#6]
go.mod文件里的包名是:
`module github.com/guonaihong/tinyws`

示例里的是 `github.com/antlabs/tinyws`
需要统一一下

**Comment by guonaihong** [comment]
我修改下。

**Comment by lesismal** [comment]
你这回复得好快啊，哈哈哈，外卖骑手在线接单的速度
新年快乐！

**Comment by guonaihong** [comment]
新年快乐哈哈。😄

**Comment by guonaihong** [comment]
好了。

**Comment by lesismal** [comment]
前阵子给我的库加上了不同的IO模式，支持每个连接一个协程、poller处理IO的混用模式，低在线量的性能和高在线量的消耗可以兼顾了。以前只有poller模式性能跑不过标准库方案，现在比gorilla要快了

**Comment by lesismal** [comment]
https://github.com/lesismal/nbio/releases/tag/v1.3.5

而且也支持直接配置开启单独的写协程，避免广播场景单个连接tcp窗口拥塞导致Write阻塞、其他连接等待的问题。

**Comment by guonaihong** [comment]
优秀，晚上我用下。测试代码是哪个仓库的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月15日(周日) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antlabs/tinyws] module name 与示例引用不一致 (Issue #6)




 
前阵子给我的库加上了不同的IO模式，支持每个连接一个协程、poller处理IO的混用模式，低在线量的性能和高在线量的消耗可以兼顾了。以前只有poller模式性能跑不过标准库方案，现在比gorilla要快了

**Comment by lesismal** [comment]
想搞http2.0/ quic/http3.0但是身体吃不消，往后排期说不定哪年有体力弄了

**Comment by lesismal** [comment]
测试还是用的这里的例子：
https://github.com/lesismal/nbio-examples/tree/master/websocket_1m

client代码随便定制改改都容易，我加了几个其他库的，整准备把你的tinyws也加进去，刚才就遇到包名不一致的问题

**Comment by lesismal** [comment]
IOModMixed或者IOModBlocking时每个连接至少一个协程的性能跟其他比gorilla快的基于标准库的框架也基本持平。

内存消耗方式不一样，nbio的内存消耗是更偏基于qps，并发度需要的buffer数量在pool里共用，每个连接上不自带一个固定的buffer；其他基于标准库的框架多数是每个连接上挂一个bufio.Reader/Writer之类的、是持续占用。
所以当连接数不大但qps很高时，nbio的内存消耗会大于其他基于标准库的框架但是在可控范围内，qps不高的话可能差不太多；但是连接数很大时，nbio的内存会保持在更低的水准，除非极端情况每个连接都tcp窗口满了之类的导致待发送的cache会占用多，但是这个值是可配置的，超过一定size当做不健康的连接自动断开连接就可以了。
另外就是IOModMixed、IOModNonBlocking，能承载更大的连接数，标准库每个连接一个协程的方式毕竟对协程数量巨大的场景还是扛不住。
